//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class books
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public books()
        {
            this.review = new HashSet<review>();
        }
    
        public int book_id { get; set; }
        public string book_name { get; set; }
        public string category { get; set; }
        public string language { get; set; }
        public Nullable<System.DateTime> publication_date { get; set; }
        public string publisher { get; set; }
        public string link { get; set; }
        public decimal price { get; set; }
        public string ImageUrl { get; set; }
        public Nullable<int> CurrentRentCount { get; set; }
        public Nullable<int> MaxRentCount { get; set; }
        public Nullable<bool> IsSold { get; set; }
        public Nullable<bool> IsRent { get; set; }
        public string author { get; set; }
    
        public virtual Borrowed_books_list Borrowed_books_list { get; set; }
        public virtual Borrowing_books Borrowing_books { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<review> review { get; set; }
    }
}
