//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Borrowing_books
    {
        public int book_id { get; set; }
        public string book_name { get; set; }
        public string category { get; set; }
        public System.DateTime date_taken { get; set; }
        public System.DateTime return_date { get; set; }
    
        public virtual books books { get; set; }
    }
}
