//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Borrowing_books
    {
        [Key]
        public float book_id { get; set; }
        public string book_name { get; set; }
        public string category { get; set; }
        public string language { get; set; }
        public string publisher { get; set; }
        public Nullable<System.DateTime> Publication_date { get; set; }
        public bool available { get; set; }
        public decimal price { get; set; }
    }
}
