//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class orders
    {
        [Key]
        public float order_number { get; set; }
        public string First_name { get; set; }
        public string Last_name { get; set; }
        public float ID { get; set; }
        public string card_owner_name { get; set; }
        public float card_number { get; set; }
        public string expird_date { get; set; }
        public float CVC { get; set; }
        public float number_of_payment { get; set; }
        public decimal price { get; set; }
        public string prodact { get; set; }
        public string Buy_Borrow { get; set; }
        public System.DateTime date { get; set; }
    }
}
