//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class review
    {
        public int ID_review { get; set; }
        public string email { get; set; }
        public string Content { get; set; }
        public string type { get; set; }
        //public Nullable<int> book_ID { get; set; }

        public int? book_ID { get; set; }

        public Nullable<System.DateTime> created_at { get; set; }
    
        public virtual books books { get; set; }
        public virtual users users { get; set; }
    }
}
