//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class waiting_list
    {
        public string name { get; set; }
        public string book_name { get; set; }
        public System.DateTime date { get; set; }
        public string email { get; set; }
    }
}
